### ISSUE TITLE
Feature: Configuration for region biasing

### ISSUE THREAD

**Issue by FrancisMurillo** [smythey21/google-geocoding-api-elixir#2]
Hello dood,

How is possible to add query parameters via configuration? Say I want to region bias my requests. Like so `:api?address=Somewhere&region=ph&key=myKey`?

**Comment by smythey21** [comment]
Hey @FrancisMurillo, very possible. But instead of adding that as a configuration option, I would probably add that as an optional argument because it's conceivable you might want to query for multiple regions. Like...

```
# I only care about Japan
geometry("123 easy st.", "JP")

# Now I'm all about that America guy
geometry("123 easy st.", "US")

# Fuck it GIVE ME ALL THE REGIONS
geometry("123 easy st.")
```

Would just need to add a bunch of defaulted arguments and edit [this line](https://github.com/smythey21/google-geocoding-api-elixir/blob/master/lib/google_geocoding_api.ex#L71), so should be pretty straight forward. Happy to accept pull requests!

**Comment by FrancisMurillo** [comment]
Marking as closed
